Transparency support
ikryukov/Strelka pull request #143
Opened 2022-02-04 10:51 UTC by jswark

2022-02-04 11:06 UTC, ikryukov requested changes

2022-02-04 11:06 UTC, ikryukov commented on shaders/lights.h
> +struct SphQuad
link to original paper

2022-02-04 11:06 UTC, ikryukov commented on shaders/lights.h
> +float2 concentricSampleDisk(float2 u) {
link to pbrt?

2022-02-04 11:06 UTC, ikryukov commented on shaders/pathtracerMdl.hlsl
> +float3 offset_ray(const float3 p, const float3 n)
offsetRay

2022-02-04 11:06 UTC, ikryukov commented on include/scene/scene.h
>      struct Light
GenericLight?

2022-02-04 11:06 UTC, ikryukov commented on include/scene/scene.h
> +        glm::float4 points[4];
data? it is not only points

2022-02-06 04:51 UTC, jswark commented on include/scene/scene.h
> +        glm::float4 points[4];
I store data apart from points:

```
glm::float4 points[4];
glm::float4 color = glm::float4(1.0f);
glm::float4 normal;
int32_t type;
```

2022-02-06 15:49 UTC, merged