update scene
ikryukov/Strelka pull request #18
Opened 2021-01-05 13:56 UTC by DoktaPola

2021-01-06 09:57 UTC, DoktaPola commented
1. Removed functions 'add' & 'remove'. 
2. Made 3 func-s : removeMesh/Instance/Material to delete one of this objects.
3. Set up clang-format

2021-01-12 17:42 UTC, DoktaPola commented
1) added several doctests (and comment some which need to be completed);
2) added "void updateInstanceTransform(uint32_t instId, glm::mat4 newTransform)" method;
3) added  "void beginFrame(), void endFrame()" methods;
4) changed "remove instance/mesh/material" methods as well as " create instance/mesh/material";

2021-01-16 17:06 UTC, ikryukov requested changes

2021-01-16 17:06 UTC, ikryukov commented on src/scene/scene.cpp
> +void MeshInstance::init_rotateBy(const float& degrees)
remove

2021-01-16 17:06 UTC, ikryukov commented on src/scene/scene.cpp
> +glm::mat4 MeshInstance::getTransformMatrix() const
float4x4& <- ref

2021-01-16 17:06 UTC, ikryukov commented on src/scene/camera.cpp
> +    return keys.left || keys.right || keys.up || keys.down;
tabs? use clang-format

2021-01-16 17:10 UTC, ikryukov commented on include/scene/scene.h
> +struct MeshInstance
remove: duplicate of Instance

2021-01-16 22:07 UTC, ikryukov requested changes

2021-01-16 22:07 UTC, ikryukov commented on src/scene/camera.cpp
> +}
new line

2021-01-16 22:07 UTC, ikryukov commented on src/scene/camera.cpp
> +    glm::mat4 rotM = glm::mat4(1.0f);
mat3 -> float4x4

2021-01-16 22:07 UTC, ikryukov commented on tests/scene/tests_scene.cpp
> +}
new line

2021-01-16 22:07 UTC, ikryukov commented on .gitignore
> +.DS_Store
new line

2021-01-17 13:28 UTC, ikryukov requested changes

2021-01-17 13:28 UTC, ikryukov commented on src/scene/scene.cpp
> +glm::mat4 Scene::createMeshTransform()
этот метод не пригодится

2021-01-17 13:28 UTC, ikryukov commented on tests/scene/tests_scene.cpp
> +    auto* scene = new nevk::Scene();
тест не проверяет логику

2021-01-17 13:28 UTC, ikryukov commented on include/scene/scene.h
> +    std::set<uint32_t> mDirtyInstances;
эти все поля в private

2021-01-17 14:23 UTC, ikryukov requested changes

2021-01-17 14:23 UTC, ikryukov commented on include/scene/scene.h
> +      struct Vertex
прокрался пробел

2021-01-17 20:14 UTC, merged