UI
ikryukov/Strelka pull request #22
Opened 2021-01-21 19:23 UTC by DoktaPola

2021-01-21 19:56 UTC, ikryukov requested changes
new lines + fix cmake

2021-01-21 19:56 UTC, ikryukov commented on src/ui/ui.cpp
> +void Ui::onResize(ImGui_ImplVulkan_InitInfo init_info, VkFormat framebufferFormat, VkDevice device, std::vector<VkImageView>& imageViews, VkPipeline graphicsPipeline, VkPipelineLayout pipelineLayout,
onResize вызывается из render (см где вызывается и для основного пасса)

2021-01-21 19:56 UTC, ikryukov commented on src/ui/ui.cpp
> +    vkDestroyPipelineLayout(device, pipelineLayout, nullptr);
у нас это не создается в явном виде, сам imgui их создает

2021-01-21 19:56 UTC, ikryukov commented on src/ui/ui.cpp
> +    // Upload Fonts
вынести в отдельную функцию uploadFonts()

2021-01-21 19:56 UTC, ikryukov commented on src/render/render.cpp
> +    // Start the Dear ImGui frame //////////////////////
создание самого UI как раз в updateUI (prepareUI) должно быть

2021-01-24 11:15 UTC, ikryukov commented on include/ui/ui.h
> +        IMGUI_CHECKVERSION();
лучше это все в init() перенести. чтобы вся инициализация в одном месте была.

2021-01-24 11:23 UTC, ikryukov commented on src/ui/ui.cpp
> +    attachment.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD; //wd.ClearEnable ? VK_ATTACHMENT_LOAD_OP_CLEAR : VK_ATTACHMENT_LOAD_OP_DONT_CARE;
VK_ATTACHMENT_LOAD_OP_DONT_CARE что тут будет правильнее?

2021-01-25 09:30 UTC, DoktaPola commented on src/ui/ui.cpp
> +    attachment.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD; //wd.ClearEnable ? VK_ATTACHMENT_LOAD_OP_CLEAR : VK_ATTACHMENT_LOAD_OP_DONT_CARE;
да, использую это значение теперь, на это и ругалось, так как неопределенные результаты предназначены для того, чтобы дать реализации свободу делать то, что она считает лучшим (она может быстро очистить, отбросить, ничего не делать ...)

2021-01-26 11:31 UTC, ikryukov requested changes

2021-01-26 11:31 UTC, ikryukov commented on CMakeLists.txt
> +endif ()
new line

2021-01-26 11:31 UTC, ikryukov commented on include/render/render.h
> +const uint32_t WIDTH = 2560;
оставьте какое-нибудь стандартное разрешение 800х600, 1280х720. Чтобы у всех помещалось на экранах.

2021-01-26 11:31 UTC, ikryukov commented on include/render/render.h
> +};
new line

2021-01-26 11:31 UTC, ikryukov commented on include/ui/ui.h
> +        //        // Release all Vulkan resources required for rendering imGui
commented code

2021-01-27 14:52 UTC, ikryukov approved these changes

2021-01-27 14:53 UTC, merged