Ms 24i
ikryukov/Strelka pull request #33
Opened 2021-03-01 16:49 UTC by DoktaPola

2021-03-01 17:07 UTC, ikryukov requested changes

2021-03-01 17:07 UTC, ikryukov commented on src/modelloader/modelloader.cpp
> +                    material.map_ambient = materials[shape.mesh.material_ids[f]].ambient_texname;
для всех тектур пока можно записать 0, а как добавится texture manager, то тут будет заполняться нужное значение.

2021-03-01 17:07 UTC, ikryukov commented on src/render/render.cpp
> +    materials.resize(sceneMaterials.size());
можно не копировать лишний раз, а использовать sceneMaterials

2021-03-01 17:07 UTC, ikryukov commented on src/render/render.cpp
> +    VkDeviceSize bufferSize = sizeof(materials[0]) * materials.size();
если вектор пустой будет, тут упадет. лучше: sizeof(Material)

2021-03-01 17:07 UTC, ikryukov commented on src/render/renderpass.cpp
> +
тут надо добавить modelToWorld и inverse model to world https://glm.g-truc.net/0.9.0/api/a00164.html

2021-03-01 17:33 UTC, DoktaPola commented on src/render/renderpass.cpp
> +
Имели ввиду эти: 
float4x4 worldToView;
float4x4 inverseWorldToView;  ?

2021-03-01 17:39 UTC, DoktaPola commented on shaders/simple.hlsl
> +    float3 ambient : COLOR0;
Здесть переменные **(float optical_density;  float shininess;  float3 transparency; uint32_t illum;)**  заполняются по типу :   
 float3 emissive = **float3(materials[inp.materialId].emissive.rgb);** ?

2021-03-01 19:17 UTC, ikryukov commented on shaders/simple.hlsl
> +    float3 ambient : COLOR0;
Да, аналогично.

2021-03-01 19:18 UTC, ikryukov commented on shaders/simple.hlsl
> +    float3 ambient : COLOR0;
Структура должна совпадать с тем что в срр коде

2021-03-01 19:18 UTC, ikryukov commented on src/render/renderpass.cpp
> +
Именно

2021-03-01 21:36 UTC, ikryukov requested changes

2021-03-01 21:36 UTC, ikryukov commented on src/render/render.cpp
> +    memcpy(data, materials.data(), (size_t)bufferSize);
sceneMaterials. сам materials тогда удалить надо.

2021-03-01 21:36 UTC, ikryukov commented on src/render/render.cpp
> +                layerFound = true;
лишнее?

2021-03-01 21:36 UTC, ikryukov commented on src/render/render.cpp
> +    //    if (vkEndCommandBuffer(cmdBuff) != VK_SUCCESS)
почему это закомменчено? как раз тут и надо команд буфер закрыть. а из UI убрать

2021-03-02 17:55 UTC, ikryukov approved these changes

2021-03-02 17:55 UTC, ikryukov commented on include/scene/scene.h
> +        float optical_density; // Ni
opticalDensity - чтобы в едином стиле было

2021-03-02 17:55 UTC, ikryukov commented on include/scene/scene.h
> +                            float optical_density,
opticalDensity

2021-03-02 17:55 UTC, ikryukov commented on src/render/render.cpp
> +    VkDeviceSize bufferSize = sizeof(nevk::Scene::Material) * sceneMaterials.size();
тут добавить проверку, что если bufferSize по каким-то причинам 0, то выйти, не делать ничего дальше.

2021-03-02 19:00 UTC, merged