Shadow mapping
ikryukov/Strelka pull request #63
Opened 2021-05-04 12:35 UTC by jswark

2021-05-05 12:50 UTC, ikryukov requested changes

2021-05-05 12:50 UTC, ikryukov commented on CMakeLists.txt
> +target_link_libraries(${UILIB_NAME} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/external/glfw/glfw3.lib")
тут нужно оставить проверку и линковать только для винды

2021-05-05 12:50 UTC, ikryukov commented on include/render/render.h
> +const uint32_t SHADOW_MAP_WIDTH = 1024;
512 достаточно

2021-05-05 12:50 UTC, ikryukov commented on include/render/shadowpass.h
> +        alignas(16) glm::mat4 modelViewProj;
эта матрица нам не пригодится для генерации карты теней

2021-05-05 12:50 UTC, ikryukov commented on include/render/shadowpass.h
> +        alignas(16) glm::float4 lightPosition;
позиция лайта тоже

2021-05-05 12:50 UTC, ikryukov commented on include/render/shadowpass.h
> +    const uint32_t SHADOW_MAP_WIDTH = 1024;
уже были объявлены константы, пусть для пасса это будут настраиваемые параметры

2021-05-05 12:50 UTC, ikryukov commented on shaders/shadow.hlsl
> +    float4 lightPosition;
эти не пригодятся

2021-05-05 12:50 UTC, ikryukov commented on shaders/shadow.hlsl
> +    out.pos = mul(mul(lightSpaceMatrix, modelViewProj), float4(vi.position, 1.0f));
тут мы умножим на матрицу modelToWorld затем переведем в lightSpace

2021-05-05 12:50 UTC, ikryukov commented on src/render/render.cpp
> +void Render::createShadowCommandBuffers()
это не используется

2021-05-05 12:50 UTC, ikryukov commented on src/render/shadowpass.cpp
> +    uboLayoutBinding.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
только вертекс, пикселя у нас не будет

2021-05-05 12:50 UTC, ikryukov commented on src/render/shadowpass.cpp
> +   // vkCmdEndRenderPass(cmd);
а где начало рендер пасса?

2021-05-05 18:08 UTC, jswark commented on shaders/shadow.hlsl
> +    out.pos = mul(mul(lightSpaceMatrix, modelViewProj), float4(vi.position, 1.0f));
Вот так? 
`out.pos = mul(lightSpaceMatrix, mul(modelToWorld, float4(vi.position, 1.0f))); `

2021-05-08 22:00 UTC, ikryukov requested changes
немного осталось

2021-05-08 22:00 UTC, ikryukov commented on shaders/simple.hlsl
> +    float closestDepth = textures[texId].Sample(shadowMap, projCoords.xy).r; //sampler2d x coord ? уыыыууууу
textures[] это у нас текстуры для материалов, для Shadow Map можно просто отдельную текстуру завести Texture2D shadowMap; и с ней работать

2021-05-08 22:00 UTC, ikryukov commented on src/render/renderpass.cpp
> +    shadowLayoutBinding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
для теней лучше отдельно текстуру + сэмплер, а не комбайнд

2021-05-08 22:00 UTC, ikryukov commented on src/render/render.cpp
> +    mShadowPass.record(cmd, vertexBuffer, indexBuffer, indicesCount, SHADOW_MAP_WIDTH, SHADOW_MAP_HEIGHT, imageIndex);
сначала рисуем глубину, потом основной наш пасс, а между ними будет барьер

2021-05-08 22:00 UTC, ikryukov commented on include/render/shadowpass.h
> +class ShadowPass
вот это не совсем теневой пасс, если быть точным - этот пасс создает текстуру глубины только (которая может быть использована в дальнейшем), а сами тени делаются после. Можно переименовать в DepthPass.

2021-05-11 18:30 UTC, ikryukov requested changes
добавить чистку (освобождение) ресурсов, чтобы дебаг леер не ругался на выходе

2021-05-11 18:30 UTC, ikryukov commented on include/render/renderpass.h
> +    void updateUniformBuffer(uint32_t currentImage, const glm::float4x4& perspective, const glm::float4x4& view, const glm::float4& lightDirect, const glm::float3& camPos, const glm::float4x4& lightS
мб тут передавать сцену, а внутри функции можно будет вытащить камеру, у камеры нужные матрицы. Да и позицию лайта тоже... будет функция покороче

2021-05-11 18:30 UTC, ikryukov commented on shaders/shadow.hlsl
> +    //out.pos = mul(mul(lightSpaceMatrix, modelToWorld), float4(vi.position, 1.0)); //?
можно удалить

2021-05-12 19:20 UTC, ikryukov requested changes

2021-05-12 19:20 UTC, ikryukov commented on shaders/simple.hlsl
> +   if (debugView == 2)
пусть тени будут как тут будут теперь в нормальном режиме, а для дебага будет чб тени. то есть dot(N, L) * shadow

2021-05-13 12:57 UTC, ikryukov requested changes

2021-05-13 12:57 UTC, ikryukov commented on src/scene/camera.cpp
> +glm::float4x4 Camera::getPerspective()
const glm::float4x4& пусть возвращает, т.к. матрица извне не должна меняться

2021-05-18 15:11 UTC, ikryukov approved these changes

2021-05-18 16:17 UTC, merged