Open scene from UI open file dialog
ikryukov/Strelka pull request #78
Opened 2021-06-18 12:25 UTC by jswark

2021-06-19 13:13 UTC, ikryukov reviewed
выделить ресурсы, которые зависят от сцены, такие как VB IB Materials... например, можно для них отдельную структуру завести и там хранить

2021-06-19 13:13 UTC, ikryukov commented on src/render/render.cpp
> +    if (!MODEL_PATH.empty())
надо как-то по-другому проверять что сцена успешно загружена - можно флаг держать...

2021-06-19 13:13 UTC, ikryukov commented on src/render/render.cpp
> +            uint32_t shId = mShaderManager.loadShader("shaders/shadowmap.hlsl", "vertexMain", nevk::ShaderManager::Stage::eVertex);
сами шейдеры у нас от сцены не зависят

2021-07-01 09:00 UTC, ikryukov requested changes

2021-07-01 18:34 UTC, ikryukov requested changes

2021-07-01 18:34 UTC, ikryukov commented on include/modelloader/modelloader.h
> +    bool isDefaultScene = false;
не используется

2021-07-01 18:34 UTC, ikryukov commented on include/render/render.h
> +    const char* csShaderCode = nullptr;
почему они вынесены, разве они нужны в классе? убрать в функцию, где используются

2021-07-01 18:34 UTC, ikryukov commented on src/render/render.cpp
> +    updatePasses();
нам не надо пересоздавать пассы или их внутренности, т.к. они не зависят от самой сцены, только обновляем дескрипторы.

2021-07-05 09:40 UTC, jswark commented on src/render/render.cpp
> +    mTexManager->textureDestroy();
save and destroy after 3 frames

2021-07-05 09:40 UTC, jswark commented on src/render/render.cpp
> +    nevk::Scene* scene = getScene();
unused

2021-07-05 09:43 UTC, jswark commented on include/render/render.h
> +        if (mScene == mDefaultScene)
use pointer only on the current scene data

2021-07-05 09:46 UTC, jswark commented on src/render/render.cpp
> +    // уыыуу
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_buffer_device_address
https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/EXT/SPV_EXT_physical_storage_buffer.html

2021-07-06 12:50 UTC, ikryukov requested changes

2021-07-06 12:50 UTC, ikryukov commented on src/resourcemanager/resourcemanager.cpp
> +        if (!buffer)
предлагаю тут использовать assert() для проверки, что указатель валиден. Внешний код обязуется не передавать нулевой, т.к. поведение не определено, а попытка вызвать с нулем это ошибка в логике. Это будет для всех функций ресурс менеджера.

2021-07-06 12:50 UTC, ikryukov commented on src/render/render.cpp
> +    if (needReload && countFrames == 3)
вместо 3 у нас была спец константа для числа кадров в полете

2021-07-09 09:05 UTC, ikryukov requested changes

2021-07-09 09:05 UTC, ikryukov commented on include/render/render.h
> +        nevk::ResourceManager* resManager = nullptr;
resManager -> mResManager
доавить конструктор в котором рес менеджер инициализируется

2021-07-09 10:46 UTC, ikryukov approved these changes

2021-07-09 10:50 UTC, merged